Document: engrid
Title: Debian engrid Manual
Author: <insert document author here>
Abstract: This manual describes what engrid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/engrid/engrid.sgml.gz

Format: postscript
Files: /usr/share/doc/engrid/engrid.ps.gz

Format: text
Files: /usr/share/doc/engrid/engrid.text.gz

Format: HTML
Index: /usr/share/doc/engrid/html/index.html
Files: /usr/share/doc/engrid/html/*.html


