.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH enGrid 1 "April 28, 2010" "" "enGrid"

.SH NAME
enGrid \- Mesh generation program.

.SH SYNOPSIS
.B engrid
.br
.B engrid
[ -f FILE ]
.br
.B engrid
[ -h ]
.br
.B engrid
[ -appendlic FILE1 FILE2 ... ]
.br
.B engrid
[ -distbin ]
.br

.SH DESCRIPTION

.PP
\fBenGrid\fP is an open-source mesh generation program.

.SH OPTIONS

.TP
.B \-f FILE
start enGrid and open FILE
.TP
.B \-h
Display usage instructions
.TP
.B \-appendlic FILE1 FILE2 ...
Append license to files
.TP
.B \-distbin
Create binary distribution

.SH AUTHOR
enGrid was written by enGits GmbH.
.PP
This manual page was written by Mike Taverne <mtaverne@engits.com>,
for the Debian project (and may be used by others).
