######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 18 16:08:45 2009
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += .

# Input
################################
#UTILITIES
INCLUDEPATH += ..
HEADERS += ../utilities.h ../error.h
SOURCES += ../utilities.cpp ../error.cpp
################################

HEADERS += dialoglineedit.h
SOURCES += dialoglineedit.cpp test.cpp
