quick:	engits.bib engrid_manual.tex gpl.tex
	pdflatex engrid_manual
full:	engits.bib engrid_manual.tex gpl.tex
	pdflatex engrid_manual
	pdflatex engrid_manual
	pdflatex engrid_manual
	bibtex engrid_manual
	pdflatex engrid_manual
	pdflatex engrid_manual
